import type { Activity, JuZhangAssignment, Registration, Settlement, TopicCard, User } from "./types";

export const users: User[] = [
  {
    id: "u-lin",
    nickname: "林夏",
    avatar: "LX",
    interests: ["日料", "城市散步", "独立书店"],
    bio: "刚换到静安上班，想认识下班后能轻松吃饭聊天的人。",
    reputationLevel: "可信参与者",
    attendedEventCount: 7,
    showAttendedEventCount: true,
    badges: ["准时到场"],
    canBeJuZhang: true,
  },
  {
    id: "u-chen",
    nickname: "陈予",
    avatar: "CY",
    interests: ["咖啡", "摄影", "展览"],
    bio: "周末喜欢找安静地方聊天，也喜欢城市观察。",
    reputationLevel: "优质参与者",
    attendedEventCount: 12,
    showAttendedEventCount: true,
    badges: ["友好破冰"],
    canBeJuZhang: true,
  },
  {
    id: "u-momo",
    nickname: "Momo",
    avatar: "MO",
    interests: ["小酒馆", "电影", "爵士"],
    bio: "喜欢低压力社交，不太想进大群。",
    reputationLevel: "新朋友",
    attendedEventCount: 1,
    showAttendedEventCount: false,
    badges: [],
    canBeJuZhang: true,
  },
  {
    id: "u-qiao",
    nickname: "乔一",
    avatar: "QY",
    interests: ["徒步", "咖啡", "设计"],
    bio: "希望认识生活节奏相近的新朋友。",
    reputationLevel: "靠谱局长",
    attendedEventCount: 18,
    showAttendedEventCount: true,
    badges: ["靠谱局长"],
    canBeJuZhang: true,
  },
];

export const activities: Activity[] = [
  {
    id: "a-sushi",
    title: "周五下班日料小局",
    type: "dinner",
    startsAt: "2026-06-05T19:30:00+08:00",
    area: "静安寺",
    venue: "若竹日料",
    budgetType: "paid",
    estimatedCost: 168,
    capacity: 6,
    currentParticipantCount: 5,
    formationStatus: "formed",
    aiRecommendationReason: "适合想下班后轻松吃饭、但不想进入大群聊天的人。",
    aaRule: "线下 AA，局长协助确认账单和支付状态。",
    cancellationRule: "普通参与者 12 小时内退出会影响内部信誉；局长接受后 24 小时内退出会触发替换。",
    privacyRule: "活动前不开放私信和联系方式，活动后双方互选才开放联系。",
    requiresSettlement: true,
    participantIds: ["u-lin", "u-chen", "u-momo", "u-qiao"],
  },
  {
    id: "a-coffee",
    title: "周末咖啡聊天局",
    type: "coffee",
    startsAt: "2026-06-06T15:00:00+08:00",
    area: "武康路",
    venue: "梧桐边咖啡",
    budgetType: "paid",
    estimatedCost: 58,
    capacity: 5,
    currentParticipantCount: 3,
    formationStatus: "nearly_full",
    aiRecommendationReason: "人数少、预算轻，适合第一次尝试陌生人轻社交。",
    aaRule: "各自点单，现场自行支付。",
    cancellationRule: "普通参与者 12 小时外可自由退出。",
    privacyRule: "只展示适度资料，不默认拉群。",
    requiresSettlement: true,
    participantIds: ["u-chen", "u-qiao"],
  },
  {
    id: "a-bar",
    title: "小酒馆微醺聊天局",
    type: "bar",
    startsAt: "2026-06-06T20:30:00+08:00",
    area: "陕西南路",
    venue: "三楼小酒馆",
    budgetType: "paid",
    estimatedCost: 120,
    capacity: 6,
    currentParticipantCount: 4,
    formationStatus: "forming",
    aiRecommendationReason: "适合愿意轻松聊天的人，系统会强调边界和安全规则。",
    aaRule: "线下 AA，不强制拼酒。",
    cancellationRule: "临近活动退出会影响内部信誉。",
    privacyRule: "活动前不开放联系方式，异常可随时反馈。",
    requiresSettlement: true,
    participantIds: ["u-lin", "u-momo"],
  },
  {
    id: "a-walk",
    title: "免费城市散步局",
    type: "walk",
    startsAt: "2026-06-07T10:00:00+08:00",
    area: "苏州河",
    venue: "四行仓库集合",
    budgetType: "free",
    estimatedCost: 0,
    capacity: 8,
    currentParticipantCount: 6,
    formationStatus: "formed",
    aiRecommendationReason: "费用为 0，适合想低门槛体验平台活动的新用户。",
    aaRule: "本活动无费用。",
    cancellationRule: "普通参与者 12 小时外可自由退出。",
    privacyRule: "活动后双方互选才开放联系方式。",
    requiresSettlement: false,
    participantIds: ["u-lin", "u-chen", "u-qiao"],
  },
];

export const registrations: Registration[] = [
  { id: "r-1", userId: "u-lin", activityId: "a-sushi", status: "confirmed", willingToBeJuZhang: true },
  { id: "r-2", userId: "u-chen", activityId: "a-sushi", status: "confirmed", willingToBeJuZhang: false },
  { id: "r-3", userId: "u-qiao", activityId: "a-sushi", status: "arrived", willingToBeJuZhang: true },
];

export const juZhangAssignments: JuZhangAssignment[] = [
  { id: "jz-1", activityId: "a-sushi", candidateUserId: "u-qiao", status: "accepted", volunteered: true },
];

export const topicCards: TopicCard[] = [
  {
    id: "topic-sushi",
    activityId: "a-sushi",
    visibleText: "如果只能把上海一个下班后最放松的地方推荐给新朋友，你会选哪里？",
  },
  {
    id: "topic-coffee",
    activityId: "a-coffee",
    visibleText: "最近有没有一个让你愿意专门出门的咖啡馆、展览或小店？",
  },
  {
    id: "topic-bar",
    activityId: "a-bar",
    visibleText: "你更喜欢热闹小酒馆，还是能安静聊天的小吧台？",
  },
  {
    id: "topic-walk",
    activityId: "a-walk",
    visibleText: "你在这座城市里最喜欢的一段路是哪一段？",
  },
];

export const settlements: Settlement[] = [
  {
    activityId: "a-sushi",
    type: "paid",
    totalAmount: 840,
    participantCount: 5,
    paymentStatusByUser: {
      "u-lin": true,
      "u-chen": true,
      "u-momo": false,
      "u-qiao": true,
    },
  },
  {
    activityId: "a-walk",
    type: "free",
    totalAmount: 0,
    participantCount: 6,
    paymentStatusByUser: {},
  },
];
